# Generated by Django 4.1.1 on 2022-10-26 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessments',
            fields=[
                ('ass_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('create_date', models.DateField(blank=True, null=True)),
                ('ass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assess.assessments')),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assess.components')),
            ],
        ),
    ]
