# Generated by Django 4.1.1 on 2022-11-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcomes',
            fields=[
                ('outcome_id', models.AutoField(primary_key=True, serialize=False)),
                ('outcome', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='components',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Subcomps',
            fields=[
                ('subcomp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assess.components')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('yes_id', models.IntegerField()),
                ('no_id', models.IntegerField()),
                ('create_date', models.DateField(blank=True, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('outcome_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assess.outcomes')),
                ('subcomp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assess.subcomps')),
            ],
        ),
    ]
