# Generated by Django 4.1.1 on 2022-11-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0002_outcomes_components_icon_subcomps_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='question_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='assess.questions'),
            preserve_default=False,
        ),
    ]
